services:
  postgres:
    image: postgres
    container_name: some-postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: db_postgres
    networks:
      - ai_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ai_web_app:
    image: ai_web_app
    container_name: ai_web_app
    networks:
      - ai_network
    ports:
      - "8080:5000"
    volumes:
      - .:/myapp
    depends_on:
      - postgres

  fast:
    image: fastapi
    container_name: fastapi
    networks:
      - ai_network
    ports:
      - "8000:8000"
    volumes:
      - .:/myapp
    depends_on:
      - postgres

networks:
  ai_network:

volumes:
  postgres_data: